$schema: "https://json.schemastore.org/eslintrc"
root: true
extends:
  - "next/core-web-vitals"
  - "prettier"
plugins:
  - "prettier-plugin-tailwindcss"
rules:
  "@next/next/no-html-link-for-pages": "off"
  "react/jsx-key": "off"
  "tailwindcss/no-custom-classname": "off"
settings:
  tailwindcss:
    callees:
      - "cn"
  next:
    rootDir:
      - "./"
    overrides:
      - files:
          - "*.ts"
          - "*.tsx"
        parser: "@typescript-eslint/parser"
